### PR TITLE
Handle escapes properly, and have syntax agree with Pandoc's math-mode

### PR DESCRIPTION
**Pull request by cbreeden**
I've created a fork to accomplish a few tasks.  I thought you might be interested in integrating some of these.

1. First upgrade KaTeX to 0.6.0
2. Have markdown-it-katex agree with the syntax provided by [pandoc](http://pandoc.org/README.html#math), which i believe is a good format to copy here.
3. Have markdown-it escape whether or not to trigger math-mode, but implement proper escaping while inside mathmode.

Here are some tests that were failing by not following syntax described by pandoc.  I think you will agree that pandoc's specifications are correct here.  None of these should be processes as math.

- `I will give you 20$, if you give me 15$ tomorrow.`
- `Thus, $20,000 and USD$30,000 won't parse as math.`
- `I will give you $20 today, if you give me more $ tomorrow.`

I have added proper inline escaping for.  It counts to number of escapes before a potential closing delimiter and then reacts appropriately.  An even number of escapes before $ means it's a potential closing delimiter, and odd number of escapes means its escaped.  I guess this only accounts for the case you end with \\\\\\\\$, a new line then escape math-mode and variants.  After second thought, maybe this part is unnecessary.  What do you think?

### CODE REVIEW

**Comment by waylonflinn** [comment]
I agree that matching pandoc is a good idea and your test cases make sense. I'll take a look at this. 
Thanks!

**Comment by cbreeden** [comment]
Yeah, I should probably take a look at it again too :)  There is probably some room for cleaning up the code a little bit too.  Let me know if you have any thoughts.

**Comment by cbreeden** [comment]
So I looked at pandoc a little harder, and I found a few more inconsistencies with what is shown here and what's given in pandoc.  The biggest of which, however, is allowing display style math inline.  Is this a deal breaker?

**Comment by waylonflinn** [comment]
When you say "allowing display style math inline" do you mean this implementation doesn't require line breaks before and after `$$`?

At this point, as long as we get closer and put tests in place to ensure we don't regress, I'll be satisfied.

**Comment by waylonflinn** [comment]
I think I see from your test, that what you meant was that this implementation does require line breaks before and after `$$`.

**Comment by cbreeden** [comment]
I agree with your sentiment.  The more I thought about it, the less I thought it was a good idea.  When Pandoc is given:

```
I like to put displaymath $$e^{i\pi} + 1 = 0$$ in the middle of my sentences for some reason.
```

it will render `$$e^{i\pi} + 1 = 0$$` in display style.  However, I feel that this goes _against_ the philosophy of markdown in general, where the rendering of markdown should largely agree with how it was written.  Even if it does not necessarily follow with how latex would render that example (it would render the math in display style).  So it probably _should_ be written as:

```
I like to put displaymath

$$ e^{i\pi} + 1 = 0 $$

in the middle of my sentences.
```

Another reason not to _strictly_ follow pandoc is that pandoc parses paragraph blocks before math.  So, for instance, the following does _not_ render as math:

```
$$
1 + 2 = 3

3 + 2 = 5
$$
```

But instead as two paragraphs.  This is probably not desirable as well.  I would agree that markdown should allow for multiline math mode in the favor of human readability.  The example you have in your Readme is a good example for why multi-line mathmode should be supported as well.

**Comment by cbreeden** [comment]
For the point of backwards compatibility, I don't think that allowing displaystyle math in inline would actually break any of the tests that are in place, so yeah, I don't know if it's a good idea or not.

**Comment by waylonflinn** [comment]
I think not allowing display math inline is reasonable. As you say, it requires the author's intent to be more clear from the markdown alone.

Can you remove the `npm-debug.log` file?

**Comment by cbreeden** [comment]
Sorry about that.

**Comment by waylonflinn** [comment]
No worries. I'll take a look at this again in the morning and, if everything looks good, I'll get it merged then.

**Pull request merged**
